# Generated by Django 2.2.6 on 2019-10-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('category', models.TextField()),
                ('stock_qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('main_image', models.FileField(upload_to='')),
                ('manufacturer', models.TextField()),
                ('ean', models.TextField()),
                ('weight', models.FloatField()),
                ('weight_measure', models.CharField(max_length=2)),
                ('flavour', models.TextField()),
                ('capsule_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsules.Capsule')),
            ],
        ),
    ]
